enum YoFonts {
  roboto,
  openSans,
  lato,
  montserrat,
  sourceSans3,
  oswald,
  raleway,
  poppins,
  ptSans,
  merriweather,
  nunito,
  rubik,
  barlow,
  bitter,
  workSans,
  inter,
  dmSans,
  playfairDisplay,
  quicksand,
  ubuntu,
  titilliumWeb,
  cabin,
  crimsonText,
  teko,
  firaSans,
  arimo,
  mukta,
  heebo,
  karla,
  abhayaLibre,
  archivo,
  asap,
  ebGaramond,
  manrope,
  overpass,
  publicSans,
  alata,
  anton,
  bebasNeue,
  josefinSans,
  lexend,
  pacifico,
  righteous,
  sora,
  spaceGrotesk,
  varelaRound,
  zillaSlab,
  fraunces,
  gelasio,
  spectral,
}

/// Digunakan untuk mengakses nama fontFamily yang sesuai
/// baik di TextStyle maupun di pubspec.yaml
const Map<YoFonts, String> yoFontFamily = {
  YoFonts.roboto: 'Roboto',
  YoFonts.openSans: 'OpenSans',
  YoFonts.lato: 'Lato',
  YoFonts.montserrat: 'Montserrat',
  YoFonts.sourceSans3: 'SourceSans3',
  YoFonts.oswald: 'Oswald',
  YoFonts.raleway: 'Raleway',
  YoFonts.poppins: 'Poppins',
  YoFonts.ptSans: 'PTSans',
  YoFonts.merriweather: 'Merriweather',
  YoFonts.nunito: 'Nunito',
  YoFonts.rubik: 'Rubik',
  YoFonts.barlow: 'Barlow',
  YoFonts.bitter: 'Bitter',
  YoFonts.workSans: 'WorkSans',
  YoFonts.inter: 'Inter',
  YoFonts.dmSans: 'DMSans',
  YoFonts.playfairDisplay: 'PlayfairDisplay',
  YoFonts.quicksand: 'Quicksand',
  YoFonts.ubuntu: 'Ubuntu',
  YoFonts.titilliumWeb: 'TitilliumWeb',
  YoFonts.cabin: 'Cabin',
  YoFonts.crimsonText: 'CrimsonText',
  YoFonts.teko: 'Teko',
  YoFonts.firaSans: 'FiraSans',
  YoFonts.arimo: 'Arimo',
  YoFonts.mukta: 'Mukta',
  YoFonts.heebo: 'Heebo',
  YoFonts.karla: 'Karla',
  YoFonts.abhayaLibre: 'AbhayaLibre',
  YoFonts.archivo: 'Archivo',
  YoFonts.asap: 'Asap',
  YoFonts.ebGaramond: 'EBGaramond',
  YoFonts.manrope: 'Manrope',
  YoFonts.overpass: 'Overpass',
  YoFonts.publicSans: 'PublicSans',
  YoFonts.alata: 'Alata',
  YoFonts.anton: 'Anton',
  YoFonts.bebasNeue: 'BebasNeue',
  YoFonts.josefinSans: 'JosefinSans',
  YoFonts.lexend: 'Lexend',
  YoFonts.pacifico: 'Pacifico',
  YoFonts.righteous: 'Righteous',
  YoFonts.sora: 'Sora',
  YoFonts.spaceGrotesk: 'SpaceGrotesk',
  YoFonts.varelaRound: 'VarelaRound',
  YoFonts.zillaSlab: 'ZillaSlab',
  YoFonts.fraunces: 'Fraunces',
  YoFonts.gelasio: 'Gelasio',
  YoFonts.spectral: 'Spectral',
};
